import pikepdf
from PIL import Image

# Paths to your files
pdf_path = "D:/cardotest/ExtractedImages/1God/God Star.pdf"           # The PDF generated by ReportLab
cover_path = "D:/cardotest/ExtractedImages/1God/cover.jpg"         # Your full cover image
output_pdf_path = "D:/cardotest/ExtractedImages/1God/God Star ITA.pdf"  # The output PDF with embedded thumbnail

# Use Pillow to get the cover image dimensions
with Image.open(cover_path) as img:
    width, height = img.size

# Open the PDF using pikepdf
pdf = pikepdf.Pdf.open(pdf_path)

# Read the cover image data
with open(cover_path, "rb") as f:
    cover_data = f.read()

# Create an image XObject for the thumbnail
thumb_obj = pdf.make_stream(cover_data)
thumb_obj.Type = pikepdf.Name("/XObject")
thumb_obj.Subtype = pikepdf.Name("/Image")
thumb_obj.Width = width
thumb_obj.Height = height
thumb_obj.ColorSpace = pikepdf.Name("/DeviceRGB")  # Adjust if your image is not RGB
thumb_obj.BitsPerComponent = 8
thumb_obj.Filter = pikepdf.Name("/DCTDecode")  # For JPEG images

# Add the thumbnail object to the PDF as an indirect object
thumb_ref = pdf.make_indirect(thumb_obj)

# Set the /Thumb key in the PDF catalog (root dictionary)
pdf.Root.Thumb = thumb_ref

# Save the updated PDF
pdf.save(output_pdf_path)
print(f"Thumbnail embedded. Saved output as {output_pdf_path}")
