name: Process JSON files with GPT

on:
  push:
    paths:
      - 'cardonaproject/raw/1God/actionstest/*.json'  # I file di input devono trovarsi in questa cartella

jobs:
  process-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install openai

      - name: Run processing script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python process_files.py
